### ISSUE TITLE
Is it possible to change the display position of the slds-dropdown list div from below the input textbox to above it?

### ISSUE THREAD

**Issue by neozhu** [pozil/sfdc-ui-lookup-lwc#133]
This change would have the benefit of not obscuring any selected items. Currently, when the user makes multiple selections, the popup dropdown list covers up the previously selected items. Since there are many items to choose from, the user would like to be able to see the first items selected to facilitate their operation.

<img width="468" alt="image" src="https://user-images.githubusercontent.com/1549611/223111860-1bfa5da5-90f8-4bc0-9f9b-a699b10aa081.png">

![image](https://user-images.githubusercontent.com/1549611/223112332-34831986-b871-4f2e-9f57-03be227e41b1.png)

**Comment by pozil** [comment]
Hi @neozhu, while I understand why you'd want this option, this is not a standard Salesforce UX so I won't implement it.
The lookup is based on the Lightning Design System blueprint and I don't want to steer away from it so that it remains maintainable:
https://www.lightningdesignsystem.com/components/lookups/?variant=listbox

**Comment by neozhu** [comment]
thank you for you information.
I made it.
![image](https://user-images.githubusercontent.com/1549611/223297003-3ce220a9-7bc1-425a-8062-38dabbeda553.png)
