### ISSUE TITLE
setDefaultResults with more than 2 items

### ISSUE THREAD

**Issue by mstohr1975** [pozil/sfdc-ui-lookup-lwc#160]
Hi there, 

as soon as setDefaultResults has a list of more than 2 items, I cannot choose the 3rd or subsequent elements. It will always fall back to the second item in selection. Is this a known issue? I couldn't find any reference

Thx

**Comment by pozil** [comment]
Hi @mstohr1975, sorry but I can't reproduce the issue. 
Here's what I did using the lookup sample app provided in this repo:
- access 4 or more accounts so that they appear in the "recently viewed" record list
- open the sample lookup (recently viewed accounts are used as default search results in this example)
- notice that you can select any of these accounts

**Comment by pozil** [comment]
Thanks for the ESC key suggestion. I've added it to the lookup and released a new version.

The invalid key issue could be caused if you supply search results or default results (`LookupSearchResult` in both case) that don't have an `id` field or if the field is null.

**Comment by pozil** [comment]
Nope, I can't reproduce. Even with a Winter '25 org.

Could it be a browser extension on your end that tries something like an autocomplete?
You could check this by trying to reproduce with a browser guest profile.

**Comment by pozil** [comment]
Ok thanks for the detailed investigation. Keep me posted.
