### ISSUE TITLE
State of pill components is not permanent

### ISSUE THREAD

**Issue by sinanbunni** [pozil/sfdc-ui-lookup-lwc#72]
Hi,
The state of the pill component is gone when a user navigates from a page to another or refreshing the page.
Is there a way to keep the selection of pills permanent on the component until the user decides to remove the pills?

Thanks,
Sinan

**Comment by pozil** [comment]
Hi @sinanbunni, thanks for reaching out. It's funny that you mention this because I just released a new version a couple of days earlier with a method that lets you save the state of the lookup or parent form. See [this doc section](https://github.com/pozil/sfdc-ui-lookup-lwc#saving-form-state-when-creating-new-records-optional).
Let me know if this answers your question.

**Comment by sinanbunni** [comment]
Thank you so much @pozil. I slipped through the documentation quickly.
